"""create_errors_table

Revision ID: 734d943bc8ca
Revises: 60d5c59adc67
Create Date: 2021-12-14 00:04:41.407963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734d943bc8ca'
down_revision = '60d5c59adc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_tag', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_id'), 'error', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_id'), table_name='error')
    op.drop_table('error')
    # ### end Alembic commands ###
